title:        Streamdata Gallery
url:          https://streamdata-gallery.github.io/apis/
raw_url: https://raw.githubusercontent.com/api-stack/market-data/master/_data/api-commons/

tag: Market Data

logo:         https://s3.amazonaws.com/kinlane-productions/api-evangelist/api-evangelist-logo-market-data.png
logo_width:   80
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

paginate: 25
paginate_path: "/blog/page:num"

github_user: api-stack
github_repo: apis
github_branch: master

collections:
  market_data:
    output: true
    permalink: /market-data/:path/
  media:
    output: true
    permalink: /media/:path/
    label: Media
  social_network:
    output: true
    permalink: /social-network/:path/
    label: Social Network
  transportation:
    output: true
    permalink: /transportation/:path/
    label: Transportation
  weather:
    output: true
    permalink: /weather/:path/
    label: Weather
  images:
    output: true
    permalink: /images/:path/
    label: Images
  developers:
    output: true
    permalink: /developers/:path/
    label: Developers
  links:
    output: true
    permalink: /links/:path/
    label: Links
  videos:
    output: true
    permalink: /videos/:path/
    label: Videos
  productivity:
    output: true
    permalink: /productivity/:path/
    label: Productivity
  analytics:
    output: true
    permalink: /analytics/:path/
    label: Analytics
  blockchain:
    output: true
    permalink: /blockchain/:path/
    label: Blockchain
  messaging:
    output: true
    permalink: /messaging/:path/
    label: Messaging
  uk_banks:
    output: true
    permalink: /uk-banks/:path/
    label: UK Banks

defaults:
  - scope:
      type: market_data
    values:
      layout: market_data
  - scope:
      type: media
    values:
      layout: media
  - scope:
      type: social_network
    values:
      layout: social_network
  - scope:
      type: transportation
    values:
      layout: transportation
  - scope:
      type: weather
    values:
      layout: weather
  - scope:
      type: images
    values:
      layout: images
  - scope:
      type: music
    values:
      layout: music
  - scope:
      type: developers
    values:
      layout: developers
  - scope:
      type: links
    values:
      layout: links
  - scope:
      type: videos
    values:
      layout: videos
  - scope:
      type: productivity
    values:
      layout: productivity
  - scope:
      type: blockchain
    values:
      layout: blockchain
  - scope:
      type: analytics
    values:
      layout: analytics
  - scope:
      type: messaging
    values:
      layout: messaging
  - scope:
      type: uk_banks
    values:
      layout: uk_banks              
